default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lumiere_development
  username: lumiere
  password: lumiere

test:
  <<: *default
  database: lumiere_test
  username: lumiere
  password: lumiere

production:
  <<: *default
  database: <%= ENV["LUMIERE_DATABASE_DATABASE"] %>
  username: <%= ENV["LUMIERE_DATABASE_USERNAME"] %>
  password: <%= ENV["LUMIERE_DATABASE_PASSWORD"] %>
